spring:
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver