spring:
  datasource:
    url:  ${DB_URL:jdbc:mysql://moon.ctiaim7daspf.ap-northeast-2.rds.amazonaws.com:3306/springtest?serverTimezone=UTC&characterEncoding=UTF-8}
    username: ${DB_USERNAME:moon}
    password: ${DB_PWD:03190319}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
  #redis:
   # host: localhost
   # port: 6379

#jwt:
 # secretKey: ${JWT_SECRET:1b2n3m5j3h5kmkc}
 # accessExp: ${JWT_ACCESS_EXP:18000}
 # refreshExp: ${JWT_REFRESH_EXP:6040800}
 # header: ${JWT_HEADER:Authorization}
 # prefix: ${JWT_PREFIX:Bearer}